Repository nephila/djangocms-page-meta, pull requests merged in 2019-03, with the labels that each got.

#101 Make tests working again
  djangocms_page_meta/cms_toolbars.py
  requirements-test.txt
  tox.ini
Labels: status: approved, type: bug

#102 Be defensive against unexpected page menu layout
  djangocms_page_meta/cms_toolbars.py
Labels: type: bug

#96 Update usage.rst
  docs/usage.rst
Labels: status: approved, type: bug, type: documentation

#97 Fix for CMS edit mode since 3.5
  .gitignore
  djangocms_page_meta/cms_toolbars.py
  tests/test_adminpage.py
  tox.ini
Labels: status: changes requested, type: bug

#98 Django 2.0 and Django 2.1 compatibility
  djangocms_page_meta/admin.py
  djangocms_page_meta/migrations/0001_initial.py
  djangocms_page_meta/migrations/0006_auto_20160423_1859.py
  djangocms_page_meta/migrations/0011_auto_20190218_1010.py
  djangocms_page_meta/models.py
  tests/test_general.py
  tests/test_templatetags.py
  tests/test_toolbar.py
  tests/test_utils/urls.py
  tox.ini
Labels: status: review, type: bug
